split_clients "${request_id}" $lb_key {
    33%    "0";
    33%    "1";
    *      "2";
}

map $lb_key $lb_host {
    "0"   python-rush-hour.onrender.com;
    "1"   10.223.70.86;
    "2"   10.223.70.86;
    default   python-rush-hour.onrender.com;
}

map $lb_key $lb_port {
    "0"   443;
    "1"   8001;
    "2"   8002;
    default   443;
}

map $lb_key $lb_scheme {
    "0"   https;
    "1"   http;
    "2"   http;
    default   https;
}

map $lb_key $lb_display_host {
    "0"   python-rush-hour.onrender.com;
    "1"   10.223.70.86;
    "2"   10.223.70.86;
    default   python-rush-hour.onrender.com;
}

server {
    listen 80;
    resolver 8.8.8.8 8.8.4.4 valid=30s ipv6=off;
    resolver_timeout 5s;

    location / {
        proxy_pass ${lb_scheme}://${lb_host}:${lb_port};
        proxy_ssl_server_name on;
        proxy_ssl_verify     off;
        proxy_set_header Host              $lb_display_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
}
